# Generated by Django 3.1.7 on 2021-03-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Android', 'Android'), ('Ios', 'Ios'), ('Web Development', 'Web Development'), ('Web Design', 'Web Design')], max_length=100),
        ),
    ]
